### PR TITLE
Esports Discord link invalid

### PR DESCRIPTION
**Pull request by zkhussain**
The previous discord link was showing as 'invalid', it probably expired. Changing it with a new one that does not expire.

### CODE REVIEW

**Comment by TheOtherUnknown** [comment]
Can you please make these changes on the current master?

**Comment by zkhussain** [comment]
Do I do that directly?

**Comment by TheOtherUnknown** [comment]
You can't. You need to base your branch on it.

**Comment by zkhussain** [comment]
I see. Do I need an approval review before doing that?

**Comment by zkhussain** [comment]
I bet making changes directly to the master can turn out pretty bad. But, isn't this branch already based on master, I'm not sure?

**Comment by TheOtherUnknown** [comment]
Yes, you need approval to make any changes to master. You need to base the branch in this PR on master, than make a PR with that. This looks like it was based on an old branch.

If that's confusing, message me Monday and I'll walk you through it. 

Closing

**Comment by zkhussain** [comment]
Ohh I understand. That's probably why it also has the previous commits. Thank you!

**Pull request closed without merging**
