### PR TITLE
Update publish.yaml

### PR DESCRIPTION
**Pull request by Cliftonz**
Updated the publish pipeline to build first then publish a release

### CODE REVIEW

**Review by AStiner — APPROVED** [review]
Why did you change from Pre-Release to Release?

**Comment by Cliftonz** [comment]
This Pipeline triggers once their is a push(merge) to master from a pull request. On that push, this pipeline should build the site and publish it as a release. This is a build up to doing CI/CD for the site and CI/CD for CSLabs in the near future.

**Comment by TheOtherUnknown** [comment]
Why are we adding GitHub's CI anyway? Is there something wrong with Travis?

**Comment by Cliftonz** [comment]
No, their is nothing wrong with Travis CI. I wanted more experience with it since my work is planning to use this in the coming years.
Also, I found I very nice plugin that publishes and release and auto increments it for you. So that's why I added GitHub CI.

**Comment by TheOtherUnknown** [comment]
That's cool, but we may want to makes changes to one or the other so the same build isn't running 3 times.

**Comment by Cliftonz** [comment]
That's good with me. 
I am having to do all of this for the Capstone this month, so I was going to use the site as our "CI/CD Prototype" so that I can do the same with CSLabs.

**Comment by Cliftonz** [comment]
I would prefer to say with GitHub Actions so everything is inside GitHub, and I am open to discuses this if you guys feel differently.

**Comment by TheOtherUnknown** [comment]
I personally don't care which one we use, as long as we stick with one. I thought GitHub Actions was still in beta, but it looks like it isn't.

**Comment by Cliftonz** [comment]
Yeah, GitHub actions and Security are out of beta now.

**Review by AStiner — APPROVED** [review]

**Review by AStiner — APPROVED** [review]

**Pull request merged**
