### PR TITLE
Delete Secretary.jpg

### PR DESCRIPTION
**Pull request by zkhussain**
Replacing it with a cropped version.

### CODE REVIEW

**Review by Cliftonz — CHANGES_REQUESTED** [review]
You should just replace the file, not delete it then open a new pullrequst.
Just replace the file with the new one, then push it to this branch.

**Comment by zkhussain** [comment]
Oh ok. Will do.

**Review by Cliftonz — APPROVED** [review]
LGTM

**Comment by Cliftonz** [comment]
Looks like a CCDCs website is failing I will go ahead and approve.

**Pull request merged**
