### PR TITLE
Make CSGLabs a jekyll style page

### PR DESCRIPTION
**Pull request by TheOtherUnknown**
I'm aware the styles aren't quite up to stuff on the new page, but that's going to require some work from someone with a better understanding of Bootstrap than me. 

@Cliftonz Everything else from #7 looks good build/Jekyll wise.

### CODE REVIEW

**Comment by TheOtherUnknown** [comment]
[Fix standard page styles for layout template](https://trello.com/c/VKhecUMZ/35-fix-standard-page-styles-for-layout-template)

**Comment by Cliftonz** [comment]
Would it be best to ask Jason about it on saturday?

**Comment by Cliftonz** [comment]
sorry wrong button

**Comment by TheOtherUnknown** [comment]
Yeah, styles may be a good thing for Barel and Jason to look into.

**Pull request merged**
